#include <iostream>
using namespace std;
main()
{
int num_1;
int num_2;
int num_3;
int num_4;
int num_5;
int num_6;
int num_7;
int num_8;
int num_9;
int num_10;
int num_11;
int num_12;
int num_13;
int num_14;
int num_15;
int add;
int subtract;
int multiply;
int total;
cout<<"enter number 1:"<<endl;  
cin>>num_1;
cout<<"enter number 2; "<<endl;
cin>>num_2;
cout<<"enter number 3: "<<endl;
cin>> num_3;
cout<<"enter number 4: "<<endl;
cin>> num_4;
cout<<"enter number 5: "<<endl;
cin>> num_5;
cout<<"enter number 6: "<<endl;
cin>> num_6;
cout<<"entr num 7: "<<endl;
cin>> num_7;
cout<<"entr num 8: "<<endl;
cin>> num_8;
cout<<"entr num 9: "<<endl;
cin>> num_9; 
cout<<"entr numbr 10: "<<endl;
cin>> num_10;
cout<<"entr num 11: "<<endl;
cin>> num_11;
cout<<"entr num 12: "<<endl;
cin>> num_12;
cout<<"entr num 13: "<<endl;
cin>> num_13;
cout<<"entr num 14: "<<endl;
cin>> num_14;
cout<<"entr num 15: "<<endl;
cin>> num_15;
add=num_1+num_5+num_2+num_3+num_4;
cout<<"value is"<<add<<endl;
subtract=num_11-num_12-num_13-num_14-num_15;
cout<<"value is"<<subtract<<endl;
multiply=num_7*num_8*num_6*num_9*num_10;
cout<<"value is"<<multiply<<endl;
total=add+multiply-subtract;
cout<<"the total is "<<total<<endl;
}

